{
 "title": "ML Inference API",
 "tags": [ "ml_inference_service" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Всего пользователей",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_users_total{job=\"ml_inference_service_api\"}",
     "legendFormat": "Пользователей"
    }
   ]
  },
  {
   "title": "Предсказаний (успешно завершённых)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_predictions_success_total{job=\"ml_inference_service_api\"}",
     "legendFormat": "Предсказаний"
    }
   ]
  },
  {
   "title": "Всего моделей",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ml_models_total{job=\"ml_inference_service_api\"}",
     "legendFormat": "Моделей"
    }
   ]
  },
  {
   "title": "Success rate предсказаний, %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ml_predictions_success_total{job=\"ml_inference_service_api\"} / (ml_predictions_success_total{job=\"ml_inference_service_api\"} + ml_predictions_failed_total{job=\"ml_inference_service_api\"})",
     "legendFormat": "Success rate (успех / (успех + ошибка))"
    }
   ]
  }
 ]
}